name: aisecureqa

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-aisecure
    restart: unless-stopped
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
      MONGO_INITDB_DATABASE: ai_secure_qa
    volumes:
      - mongo_aisecure_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongo_aisecure_data: